from source.pages.base_page import *


a=launch()
def pim_hrm():


    a.find_element_by_xpath("//*[@id='menu_pim_viewPimModule']").click()
    a.find_element_by_id("menu_pim_viewEmployeeList").click()
    name = a.find_element_by_id("empsearch_employee_name_empName")
    time.sleep(5)
    name.send_keys("Parthu")
    id = a.find_element_by_id("empsearch_id")
    id.send_keys("143")
    supervisore = a.find_element_by_id("empsearch_supervisor_name")
    supervisore.send_keys("Kishore")
    job_title = Select(a.find_element_by_id("empsearch_job_title"))
    job_title.select_by_visible_text("QA Engineer")
    emp_status =Select(a.find_element_by_xpath("/html/body/div[1]/div[3]/div[1]/div[2]/form/fieldset/ol/li[3]/select"))
    emp_status.select_by_visible_text("Part-Time Contract")
    sub_unit = Select(a.find_element_by_xpath("/html/body/div[1]/div[3]/div[1]/div[2]/form/fieldset/ol/li[7]/select"))
    sub_unit.select_by_visible_text("Engineering")
    include = Select(a.find_element_by_xpath("/html/body/div[1]/div[3]/div[1]/div[2]/form/fieldset/ol/li[4]/select"))
    include.select_by_visible_text("Past Employees Only")
    time.sleep(5)
    click = a.find_element_by_id("searchBtn").click()
    time.sleep(4)
    add = a.find_element_by_id("btnAdd").click()
    time.sleep(4)
    first_name = a.find_element_by_id("firstName")
    first_name.send_keys("Madhu ")
    sec_name = a.find_element_by_id("middleName")
    sec_name.send_keys("parthu")
    last_name = a.find_element_by_id("lastName")
    last_name.send_keys("Midde")
    emp_id = a.find_element_by_id("employeeId").clear()
    emp_id2 = a.find_element_by_id("employeeId").send_keys("143")
    photo = a.find_element_by_id("photofile")
    photo.send_keys("C:\\Users\\parthu\\OneDrive\\Pictures\\Screenshots\\IMG_20201014_182810.jpg")
    login = a.find_element_by_id("chkLogin").click()
    time.sleep(2)
    user = a.find_element_by_id("user_name")
    time.sleep(3)
    user.send_keys("parthudj021@gmail.com")
    password = a.find_element_by_id("user_password")
    time.sleep(3)
    password.send_keys("Parthu@123")
    con_psw = a.find_element_by_id("re_password")
    time.sleep(3)
    con_psw.send_keys("Parthu@123")
    status = Select(a.find_element_by_id("status"))
    status.select_by_visible_text("Disabled")

    time.sleep(2)
    save= a.find_element_by_id("btnSave").click()
    time.sleep(2)
    edit=a.find_element_by_xpath("//*[@id='btnSave']").click()
    license=a.find_element_by_xpath("/html/body/div[1]/div[3]/div/div[2]/div[2]/form/fieldset/ol[2]/li[3]/input")
    license.send_keys("99887766")
    ssn=a.find_element_by_xpath("//*[@id='personal_txtNICNo']")
    ssn.send_keys("123456")
    other_id=a.find_element_by_id("personal_txtOtherID")
    other_id.send_keys("332211")
    date=a.find_element_by_id("personal_txtLicExpDate").clear()
    date2 = a.find_element_by_id("personal_txtLicExpDate").send_keys("2021-10-19")
    sin_number=a.find_element_by_id("personal_txtSINNo")
    sin_number.send_keys("549719")
    gender=a.find_element_by_id("personal_optGender_1").click()
    national=Select(a.find_element_by_id("personal_cmbNation"))
    national.select_by_visible_text("Indian")
    marital=Select(a.find_element_by_id("personal_cmbMarital"))
    marital.select_by_visible_text("Single")
    DOB=a.find_element_by_id("personal_DOB").clear()
    DOB2 = a.find_element_by_id("personal_DOB").send_keys("1998-10-19")
    nic_name=a.find_element_by_id("personal_txtEmpNickName")
    nic_name.send_keys("rickky")
    miletry=a.find_element_by_id("personal_txtMilitarySer")
    miletry.send_keys("no")
    button=a.find_element_by_id("btnSave").click()
    button=a.find_element_by_id("btnSave").click()




pim_hrm()
